# Generated by Django 5.1.4 on 2025-03-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, default='public', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, default='public', max_length=50)),
                ('discovered_on', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='dashboardapp.device')),
            ],
        ),
    ]
