# Generated by Django 5.1.4 on 2025-03-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
