# Generated by Django 5.1.4 on 2025-03-24 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_deviceresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='bandwidth_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='bandwidth_out',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='last_in_octets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='last_out_octets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='last_polled',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='utilization_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='utilization_out',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
