#all devices (router, L3switches, L2Switch) in groups, with ip address and login info.

all:
  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco

  children:
    switches:
       hosts:
        ManagementSwitch:
          ansible_host: 192.168.10.5
        L3Switch1:
          ansible_host: 192.168.10.6
        L3Switch2:
          ansible_host: 192.168.10.7
        L3Switch3:
          ansible_host: 192.168.10.8
        L3Switch4:
          ansible_host: 192.168.10.9
        L2Switch1:
          ansible_host: 192.168.10.12
        L2Switch2:
          ansible_host: 192.168.10.13
        

    routers:
      hosts:
        CoreRouter1:
          ansible_host: 192.168.10.10
        CoreRouter2:
          ansible_host: 192.168.10.11

  
   
        
