---
- name: Console Password Setup
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Set console line password
      ios_config:
        lines:
          - password {{ console_password }}
          - login
        parents: line console 0
