- name: VTY Password Setup
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure VTY line password
      ios_config:
        lines:
          - "line vty 0 4"
          - "password {{ vty_password }}"
          - "login"
