# Generated by Django 5.1.4 on 2025-03-26 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboardapp', '0004_networkinterface_bandwidth_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('PING', 'Ping Device'), ('HOSTNAME', 'Change Hostname'), ('VLAN', 'Configure VLAN'), ('ACL', 'Implement ACL')], max_length=20)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_tasks', to='dashboardapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='networkmanagement.configurationtask')),
            ],
        ),
    ]
